"""Freshness contract-pin for the committed env code-reference snapshot.

``app/data/env_coderefs.json`` is generated by ``app/gen_env_coderefs.py`` (a
static AST scan of each service's runtime source) and read at request time by
``app/codedrift.py`` — the deployed control-plane ships only ``app/`` and can
never re-scan the other services, so the snapshot IS the source of truth for
"what the code reads". This pins it: add or remove an ``os.getenv`` /
``os.environ`` reference without regenerating, and the build fails here with the
regenerate instruction. Also asserts the snapshot is names-only and covers
exactly the four services.
"""

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app import gen_env_coderefs  # noqa: E402

_NAME_RE = re.compile(r"^[A-Z][A-Z0-9_]+$")


def test_committed_snapshot_matches_a_fresh_scan():
    """The committed JSON must byte-equal a fresh render — the exact --check
    the generator performs, surfaced as a unit test."""
    assert gen_env_coderefs.main(["--check"]) == 0, (
        "app/data/env_coderefs.json is STALE — run "
        "`python3 -m app.gen_env_coderefs`"
    )


def test_snapshot_covers_the_four_services():
    snap = json.loads(gen_env_coderefs.SNAPSHOT_PATH.read_text(encoding="utf-8"))
    assert set(snap["services"]) == set(gen_env_coderefs.SERVICE_PACKAGES.values())


def test_snapshot_is_names_only():
    """Every recorded entry is an env-var NAME (upper-snake), never a value."""
    snap = json.loads(gen_env_coderefs.SNAPSHOT_PATH.read_text(encoding="utf-8"))
    for svc, names in snap["services"].items():
        assert names == sorted(names), f"{svc} names not sorted"
        for name in names:
            assert _NAME_RE.match(name), f"{svc}: {name!r} is not env-name-shaped"


def test_scanner_resolves_the_three_reference_shapes():
    """The scan resolves direct literals, _env* wrapper args, and module-
    constant indirection (the patterns the real source actually uses)."""
    src = (
        "import os\n"
        "ENV_KEY = 'ANTHROPIC_API_KEY'\n"
        "def _env_int(name, d):\n"
        "    return int(os.environ.get(name) or d)\n"
        "A = os.getenv('DIRECT_VAR')\n"
        "B = os.environ['SUBSCRIPT_VAR']\n"
        "C = _env_int('WRAPPED_VAR', 5)\n"
        "D = os.environ.get(ENV_KEY)\n"
        "junk = some_func('lowercase_not_a_var')\n"
    )
    names = gen_env_coderefs.names_in_source(src)
    assert names == {
        "DIRECT_VAR", "SUBSCRIPT_VAR", "WRAPPED_VAR", "ANTHROPIC_API_KEY",
    }
